name: Build - GitHub Actions Workflow
# Define when the workflow should be triggered
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - "*"

# Define jobs for the workflow
jobs:
  # Job: Build
  build:
    runs-on: alpine-latest
    # Steps for the build job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build